function HeroDemo()
% ASPICE SWE.4-6 test dashboard demo for the README hero GIF

plotFiles = generateAllPlots();


darkBg = [0.06 0.06 0.08];
fig = uifigure( ...
    "Name", "Test Dashboard", ...
    "Position", [80 60 1440 860], ...
    "Color", darkBg);
gl = uigridlayout(fig, ...
    "RowHeight", {'1x'}, ...
    "ColumnWidth", {'1x'}, ...
    "Padding", [0 0 0 0], ...
    "BackgroundColor", darkBg);

frame = ic.Frame("Parent", gl);
frame.ColorScheme = "dark";
frame.css.style("", "backgroundColor", "#0e0e14", "fontFamily", ...
    "'Inter', 'Segoe UI', system-ui, sans-serif");

root = ic.FlexContainer("Direction", "column", "Gap", 0, "Padding", 0);
frame.addChild(root);
root.css.fill();

sidebar = buildSidebar(frame);
header = buildHeader(root);
[tc, kpiRow, tbl, drawer] = buildContent(root, frame, plotFiles);
applyStyle(header, tbl, kpiRow);
wireCallbacks(header, tc, tbl, drawer, frame, sidebar);

% -- sidebar ---------------------------------------------------------------

function sb = buildSidebar(frame)
    sb.drawer = ic.Drawer( ...
        "Title", "Test Suite", ...
        "Side", "left", ...
        "Size", "sm", ...
        "Overlay", true, ...
        "Closable", true);
    frame.addChild(sb.drawer);

    nav = ic.FlexContainer("Direction", "column", "Gap", 4, "Padding", [8 12]);
    sb.drawer.Body.addChild(nav);

    sections = ["Overview", "Report", "Architecture"];
    icons = ["layout-dashboard", "file-text", "git-branch"];
    sb.navBtns = {};
    for i = 1:numel(sections)
        btn = ic.Button( ...
            "Label", sections(i), ...
            "Variant", "secondary", ...
            "Fill", "ghost", ...
            "Size", "md");
        btn.Icon = ic.Icon("Source", icons(i), "Size", "sm");
        nav.addChild(btn);
        btn.css.style("", "justifyContent", "flex-start", "width", "100%");
        if i == 1
            btn.css.style("", ...
                "backgroundColor", "rgba(99,102,241,0.12)", ...
                "color", "#818cf8");
        end
        sb.navBtns{i} = btn;
    end

    sb.drawer.Body.addChild(ic.Label("Text", ""));
    sb.drawer.Body.css.style("", "display", "flex", "flexDirection", "column");

    tree = ic.Tree("Size", "sm", "Selectable", false);
    sb.drawer.Body.addChild(tree);
    tree.css.style("", "marginTop", "auto", "opacity", "0.6", "fontSize", "12px");

    swe4 = ic.tree.Node("SWE.4 Unit", Icon = "box");
    swe4.add("Motor Control",    Icon = "cpu");
    swe4.add("Sensor Fusion",    Icon = "cpu");
    swe4.add("Diagnostics",      Icon = "cpu");
    swe5 = ic.tree.Node("SWE.5 Integration", Icon = "git-merge");
    swe5.add("CAN Stack",        Icon = "network");
    swe5.add("Power Management", Icon = "zap");
    swe6 = ic.tree.Node("SWE.6 Qualification", Icon = "shield-check");
    swe6.add("Safety (ASIL-B)",  Icon = "alert-triangle");
    swe6.add("HIL Regression",   Icon = "monitor");
    tree.Items = [swe4, swe5, swe6];
    tree.expandAll();
end

% -- header ----------------------------------------------------------------

function h = buildHeader(parent)
    h.row = ic.FlexContainer( ...
        "Direction", "row", "Gap", 12, ...
        "Padding", [10 20], "AlignItems", "center");
    parent.addChild(h.row);

    h.menuBtn = ic.Button( ...
        "Label", "", "Variant", "secondary", "Fill", "ghost", "Size", "sm");
    h.menuBtn.Icon = ic.Icon("Source", "menu", "Size", "sm");
    h.row.addChild(h.menuBtn);

    h.title = ic.Label( ...
        "Text", "Test Dashboard", ...
        "Variant", "heading", "Size", "lg", "Weight", "bold");
    h.row.addChild(h.title);

    spacer = ic.Label("Text", "");
    h.row.addChild(spacer);
    spacer.css.style("", "flex", "1");

    h.search = ic.SearchBar( ...
        "Placeholder", "Filter tests...", ...
        "Clearable", true, "Size", "sm");
    h.row.addChild(h.search);
    h.search.css.style("", "maxWidth", "280px", "flex", "1");

    h.themeToggle = ic.Switch("Value", true, "Size", "sm");
    h.row.addChild(h.themeToggle);
end

% -- main content ----------------------------------------------------------

function [tc, kpiRow, tbl, drawer] = buildContent(parent, frame, plotFiles)
    tc.container = ic.TabContainer("Size", "md", "DragEnabled", true);
    parent.addChild(tc.container);
    tc.container.css.fill();
    tc.container.css.style(".ic-tc__label", "whiteSpace", "nowrap");

    % overview tab
    [p1, tc.overviewTab] = tc.container.addTab("Overview", Icon = "layout-dashboard");
    overview = ic.FlexContainer("Direction", "column", "Gap", 16, "Padding", [16 20]);
    p1.addChild(overview);
    overview.css.fill();

    kpiRow = buildKpiCards(overview);
    tbl = buildTable(overview);

    % report tab
    [p2, tc.reportTab] = tc.container.addTab("Report", Icon = "file-text");
    buildReportTab(p2, plotFiles);

    % architecture tab
    [p3, tc.archTab] = tc.container.addTab("Architecture", Icon = "git-branch");
    buildArchTab(p3);

    % detail drawer
    drawer = buildDetailDrawer(frame);
end

% -- KPI cards -------------------------------------------------------------

function kpi = buildKpiCards(parent)
    kpi.row = ic.GridContainer( ...
        "Columns", "repeat(4, 1fr)", "Gap", 14);
    parent.addChild(kpi.row);
    kpi.row.css.style("", "width", "100%");

    cards = { ...
        "Pass Rate",      "94.2%",  94, "success",     "check-circle"; ...
        "Code Coverage",  "81.7%",  82, "primary",     "layers"; ...
        "Req. Coverage",  "76%",    76, "warning",     "list-checks"; ...
        "Open Defects",   "12",     88, "destructive", "bug"};

    kpi.progress = {};
    for i = 1:size(cards, 1)
        [card, cpb] = makeKpiCard(cards{i, :});
        kpi.row.addChild(card);
        kpi.progress{i} = cpb;
    end
end

function [card, cpb] = makeKpiCard(label, value, pct, variant, iconName)
    card = ic.FlexContainer( ...
        "Direction", "row", "Gap", 16, ...
        "Padding", [16 20], "AlignItems", "center");

    cpb = ic.CircularProgressBar( ...
        "Value", pct, "Size", "md", ...
        "Variant", variant, ...
        "ShowLabel", true, "LabelFormat", "%d%%", ...
        "StrokeWidth", 5, "LineCap", "round");
    card.addChild(cpb);

    col = ic.FlexContainer("Direction", "column", "Gap", 4, "Padding", [0 8]);
    card.addChild(col);
    col.css.style("", "flex", "1", "minWidth", "0");

    lbl = ic.Label("Text", label, "Size", "sm");
    col.addChild(lbl);
    lbl.css.style("", "color", "rgba(255,255,255,0.45)", "fontSize", "11px", ...
        "textTransform", "uppercase", "letterSpacing", "0.5px");

    val = ic.Label("Text", value, "Size", "xl", "Weight", "bold");
    col.addChild(val);
    val.css.style("", "color", "#e2e8f0");

    ico = ic.Icon("Source", iconName, "Size", "sm");
    card.addChild(ico);
    ico.css.style("", "marginLeft", "auto", "color", "rgba(255,255,255,0.25)");
end

% -- table -----------------------------------------------------------------

function tbl = buildTable(parent)
    tbl = ic.Table( ...
        "Striped", true, ...
        "Selectable", true, ...
        "ShowRowNumbers", true, ...
        "Size", "sm");
    parent.addChild(tbl);
    tbl.css.style("", "flex", "1", "minHeight", "0");

    tbl.Columns = [ ...
        ic.table.EnumColumn("Result", ...
            "Width", 85, "Filterable", true, ...
            "Items", ["Pass", "Fail", "Blocked", "Skip"], ...
            "Colors", ["#22c55e", "#ef4444", "#f59e0b", "#6b7280"])

        ic.table.TextColumn("TestCase", ...
            "Header", "Test Case", ...
            "Width", 260, "Sortable", true, "Filterable", true)

        ic.table.EnumColumn("Level", ...
            "Width", 75, "Filterable", true, ...
            "Items", ["SWE.4", "SWE.5", "SWE.6"], ...
            "Colors", ["#3b82f6", "#8b5cf6", "#ec4899"])

        ic.table.TextColumn("Module", ...
            "Width", 130, "Sortable", true, "Filterable", true)

        ic.table.EnumColumn("Priority", ...
            "Width", 75, "Filterable", true, ...
            "Items", ["ASIL-B", "QM"], ...
            "Colors", ["#ef4444", "#6b7280"])

        ic.table.ProgressBarColumn("Coverage", ...
            "Min", 0, "Max", 100, "Width", 130, ...
            "ShowLabel", true, "LabelFormat", "%d%%", ...
            "Variant", "primary", ...
            "ColorRules", [ ...
                ic.table.ColorRule(">=", 80, "#22c55e") ...
                ic.table.ColorRule(">=", 60, "#f59e0b") ...
                ic.table.ColorRule("<",  60, "#ef4444")])

        ic.table.SparklineColumn("Duration", ...
            "Header", "Duration (5 runs)", "Width", 130, ...
            "LineWidth", 1.5, "FillArea", true, ...
            "ShowEndDot", true, "Metric", "relative", ...
            "ColorRules", [ ...
                ic.table.ColorRule(">=", 0, "#4ade80") ...
                ic.table.ColorRule("<",  0, "#f87171")])

        ic.table.DateColumn("LastRun", ...
            "Header", "Last Run", ...
            "Width", 100, "Sortable", true, ...
            "Format", "short")
    ];

    tbl.Data = generateTestData();
end

function T = generateTestData()
    rng(7);
    n = 20;

    tests = [ ...
        "TC_MotCtrl_Torque_Limit", "TC_MotCtrl_Ramp_Rate", "TC_MotCtrl_Overcurrent", ...
        "TC_SensFus_Kalman_Init", "TC_SensFus_GPS_Timeout", "TC_SensFus_IMU_Drift", ...
        "TC_Diag_DTC_Storage", "TC_Diag_Snapshot_Capture", "TC_Diag_Clear_All", ...
        "TC_CAN_Msg_Timeout", "TC_CAN_Bus_Off_Recovery", "TC_CAN_DLC_Validation", ...
        "TC_PwrMgmt_Sleep_Entry", "TC_PwrMgmt_Wakeup_Source", "TC_PwrMgmt_Undervoltage", ...
        "TC_Safety_Watchdog_Trip", "TC_Safety_ASIL_Decomp", "TC_Safety_E2E_CRC", ...
        "TC_HIL_Regression_Full", "TC_HIL_Timing_Jitter"]';

    modules = [ ...
        "Motor Control", "Motor Control", "Motor Control", ...
        "Sensor Fusion", "Sensor Fusion", "Sensor Fusion", ...
        "Diagnostics", "Diagnostics", "Diagnostics", ...
        "CAN Stack", "CAN Stack", "CAN Stack", ...
        "Power Mgmt", "Power Mgmt", "Power Mgmt", ...
        "Safety", "Safety", "Safety", ...
        "HIL", "HIL"]';

    levels = [ ...
        "SWE.4","SWE.4","SWE.4", ...
        "SWE.4","SWE.4","SWE.4", ...
        "SWE.4","SWE.4","SWE.4", ...
        "SWE.5","SWE.5","SWE.5", ...
        "SWE.5","SWE.5","SWE.5", ...
        "SWE.6","SWE.6","SWE.6", ...
        "SWE.6","SWE.6"]';

    results = ["Pass","Fail","Blocked","Skip"];
    weights = [0.70, 0.12, 0.10, 0.08];
    cumW = cumsum(weights);
    Result = strings(n, 1);
    for i = 1:n
        r = rand();
        Result(i) = results(find(r <= cumW, 1));
    end
    Result(1) = "Pass"; Result(4) = "Pass"; Result(10) = "Fail";
    Result(16) = "Pass"; Result(19) = "Blocked";

    TestCase = tests;
    Level = levels;
    Module = modules;

    Priority = strings(n, 1);
    for i = 1:n
        if contains(Module(i), "Safety") || Level(i) == "SWE.6"
            Priority(i) = "ASIL-B";
        else
            Priority(i) = "QM";
        end
    end

    Coverage = randi([45 98], n, 1);
    Coverage(Result == "Pass") = randi([75 98], sum(Result == "Pass"), 1);
    Coverage(Result == "Fail") = randi([30 70], sum(Result == "Fail"), 1);

    Duration = cell(n, 1);
    for i = 1:n
        base = 0.5 + 4*rand();
        Duration{i} = base + 0.3*randn(1, 5);
    end

    LastRun = datetime(2026, 4, 1) + days(randi(11, n, 1));

    T = table(Result, TestCase, Level, Module, Priority, Coverage, Duration, LastRun);
end

% -- report tab (figures grid + Typst document) ----------------------------

function buildReportTab(panel, plotFiles)
    row = ic.FlexContainer("Direction", "row", "Gap", 0, "Padding", 0);
    panel.addChild(row);
    row.css.fill();

    % left: 6 test-related figures in a 3x2 grid
    figGrid = ic.GridContainer( ...
        "Columns", "1fr 1fr", "Rows", "1fr 1fr 1fr", "Gap", 8);
    row.addChild(figGrid);
    figGrid.css.style("", "flex", "1", "padding", "12px", "minWidth", "0");
    for i = 1:6
        img = ic.Image("Source", plotFiles(i), "ObjectFit", "contain");
        figGrid.addChild(img);
        img.css.style("", ...
            "borderRadius", "6px", ...
            "border", "1px solid rgba(255,255,255,0.06)", ...
            "backgroundColor", "rgba(255,255,255,0.02)");
    end

    % right: Typst test report
    typstDoc = ic.Typst( ...
        "Value", buildTypstSource(plotFiles(1), plotFiles(5)), ...
        "ToolbarOnHover", true);
    row.addChild(typstDoc);
    typstDoc.css.style("", "flex", "1", "minWidth", "0");
end

function files = generateAllPlots()
    outDir = fullfile(tempdir, "hero_plots");
    if ~isfolder(outDir), mkdir(outDir); end

    darkBg = [0.06 0.06 0.08];
    axBg   = [0.08 0.09 0.12];
    gridC  = [0.2 0.2 0.25];
    axC    = [0.45 0.45 0.5];
    titleC = [0.88 0.88 0.92];

    rng(42);
    files = strings(1, 6);

    % create all 6 figures first
    figs = gobjects(1, 6);
    for idx = 1:6
        f = figure("Visible", "off", "Color", darkBg, ...
            "Position", [100 100 520 340]);
        ax = axes(f, "Color", axBg, "XColor", axC, "YColor", axC, ...
            "GridColor", gridC, "GridAlpha", 0.4, "Box", "off");
        hold(ax, "on");
        grid(ax, "on");

        switch idx
            case 1  % coverage trend over sprints
                sprints = 1:10;
                stmt = [62 65 68 71 74 76 78 80 81 82];
                branch = [48 51 55 58 60 63 65 68 70 72];
                mcdc = [30 33 37 40 44 48 51 55 58 61];
                plot(ax, sprints, stmt,   "-o", "Color", [0.39 0.45 0.96], "LineWidth", 2, "MarkerSize", 4);
                plot(ax, sprints, branch, "-s", "Color", [0.13 0.77 0.37], "LineWidth", 2, "MarkerSize", 4);
                plot(ax, sprints, mcdc,   "-^", "Color", [0.97 0.62 0.17], "LineWidth", 2, "MarkerSize", 4);
                yline(ax, 80, "--", "Color", [0.9 0.3 0.3], "LineWidth", 1, "Alpha", 0.6);
                legend(ax, "Statement", "Branch", "MC/DC", "Target", ...
                    "TextColor", [0.7 0.7 0.75], "Color", axBg, "EdgeColor", gridC);
                title(ax, "Coverage Trend (per Sprint)", "Color", titleC);
                xlabel(ax, "Sprint"); ylabel(ax, "%");
                ylim(ax, [20 100]);

            case 2  % pass/fail/blocked per module (stacked bar)
                mods = categorical(["MotCtrl","SensFus","Diag","CAN","PwrMgmt","Safety","HIL"]);
                mods = reordercats(mods, ["MotCtrl","SensFus","Diag","CAN","PwrMgmt","Safety","HIL"]);
                data = [8 6 7 5 4 6 3;   % pass
                        1 2 1 2 1 0 1;   % fail
                        0 1 0 1 1 1 2;   % blocked
                        1 0 1 0 0 0 0]'; % skip
                b = bar(ax, mods, data, "stacked");
                b(1).FaceColor = [0.13 0.77 0.37];
                b(2).FaceColor = [0.94 0.27 0.27];
                b(3).FaceColor = [0.97 0.62 0.17];
                b(4).FaceColor = [0.45 0.45 0.5];
                legend(ax, "Pass", "Fail", "Blocked", "Skip", ...
                    "TextColor", [0.7 0.7 0.75], "Color", axBg, "EdgeColor", gridC);
                title(ax, "Results by Module", "Color", titleC);
                ylabel(ax, "Test Cases");

            case 3  % scatter: coverage vs execution time
                cov = 40 + 55*rand(50, 1);
                dur = 0.5 + 5*rand(50, 1);
                colors = zeros(50, 3);
                for k = 1:50
                    if cov(k) >= 80
                        colors(k,:) = [0.13 0.77 0.37];
                    elseif cov(k) >= 60
                        colors(k,:) = [0.97 0.62 0.17];
                    else
                        colors(k,:) = [0.94 0.27 0.27];
                    end
                end
                scatter(ax, cov, dur, 35, colors, "filled", "MarkerFaceAlpha", 0.7);
                title(ax, "Coverage vs Duration", "Color", titleC);
                xlabel(ax, "Coverage (%)"); ylabel(ax, "Duration (s)");

            case 4  % area: defects open/closed over time
                weeks = 1:12;
                opened = [5 8 4 6 3 7 5 4 2 3 4 2];
                closed = [2 5 6 5 4 6 7 5 3 4 5 3];
                area(ax, weeks, opened, "FaceColor", [0.94 0.27 0.27], ...
                    "FaceAlpha", 0.3, "EdgeColor", [0.94 0.27 0.27], "LineWidth", 1.5);
                area(ax, weeks, closed, "FaceColor", [0.13 0.77 0.37], ...
                    "FaceAlpha", 0.3, "EdgeColor", [0.13 0.77 0.37], "LineWidth", 1.5);
                legend(ax, "Opened", "Closed", ...
                    "TextColor", [0.7 0.7 0.75], "Color", axBg, "EdgeColor", gridC);
                title(ax, "Defect Trend (12 weeks)", "Color", titleC);
                xlabel(ax, "Week"); ylabel(ax, "Count");

            case 5  % bar: requirement traceability
                cats = categorical(["SWE.4", "SWE.5", "SWE.6"]);
                cats = reordercats(cats, ["SWE.4", "SWE.5", "SWE.6"]);
                traced = [142 68 34];
                total  = [165 82 45];
                b = bar(ax, cats, [traced; total-traced]', "stacked");
                b(1).FaceColor = [0.39 0.45 0.96];
                b(2).FaceColor = [0.25 0.25 0.3];
                legend(ax, "Traced", "Untraceable", ...
                    "TextColor", [0.7 0.7 0.75], "Color", axBg, "EdgeColor", gridC);
                title(ax, "Requirement Traceability", "Color", titleC);
                ylabel(ax, "Requirements");

            case 6  % histogram: test execution times
                times = 0.5 - 2*log(rand(300, 1));
                histogram(ax, times, 25, ...
                    "FaceColor", [0.51 0.36 0.84], "EdgeColor", "none", ...
                    "FaceAlpha", 0.7);
                xline(ax, 5, "--", "Color", [0.9 0.3 0.3], "LineWidth", 1.5, "Alpha", 0.7);
                title(ax, "Execution Time Distribution", "Color", titleC);
                xlabel(ax, "Duration (s)"); ylabel(ax, "Count");
        end
        figs(idx) = f;
    end

    % batch export all at once, then close
    for idx = 1:6
        fname = fullfile(outDir, sprintf("plot_%d.png", idx));
        print(figs(idx), fname, "-dpng", "-r150");
        files(idx) = fname;
    end
    close(figs);
end

function src = buildTypstSource(coveragePlot, traceabilityPlot)
    NL = newline;
    src = ...
        "#import ""@preview/oxdraw:0.1.0"": *" + NL + ...
        NL + ...
        "#set page(fill: rgb(""#0e0e14""), margin: 1.5cm)" + NL + ...
        "#set text(fill: rgb(""#e2e8f0""), size: 10.5pt)" + NL + ...
        "#set heading(numbering: ""1."")" + NL + ...
        NL + ...
        "#align(center)[" + NL + ...
        "  #text(size: 20pt, weight: ""bold"")[ASPICE SWE.4--6 Test Report]" + NL + ...
        "  #v(4pt)" + NL + ...
        "  #text(size: 10pt, fill: rgb(""#94a3b8""))[Sprint 10 -- April 12, 2026 -- CONFIDENTIAL]" + NL + ...
        "]" + NL + ...
        NL + ...
        "#v(12pt)" + NL + ...
        NL + ...
        "= Summary" + NL + ...
        NL + ...
        "This report covers verification activities for SWE.4 (Unit), SWE.5 (Integration), " + ...
        "and SWE.6 (Qualification) per ASPICE v4.0. A total of *292 test cases* were " + ...
        "executed across 7 modules. Overall pass rate stands at *94.2%* with *12 open " + ...
        "defects* remaining." + NL + ...
        NL + ...
        "= Coverage Metrics" + NL + ...
        NL + ...
        "#table(" + NL + ...
        "  columns: (2fr, 1fr, 1fr, 1fr, 1fr)," + NL + ...
        "  stroke: rgb(""#1e293b"")," + NL + ...
        "  fill: rgb(""#12121a"")," + NL + ...
        "  table.header(" + NL + ...
        "    [*Module*], [*Statement*], [*Branch*], [*MC/DC*], [*Req. Traced*]," + NL + ...
        "  )," + NL + ...
        "  [Motor Control], [92%], [84%], [71%], [38/42]," + NL + ...
        "  [Sensor Fusion], [87%], [76%], [62%], [31/35]," + NL + ...
        "  [Diagnostics],   [85%], [71%], [58%], [28/33]," + NL + ...
        "  [CAN Stack],     [78%], [68%], [54%], [24/30]," + NL + ...
        "  [Power Mgmt],    [81%], [73%], [60%], [21/25]," + NL + ...
        "  [Safety],        [94%], [88%], [76%], [32/34]," + NL + ...
        "  [HIL],           [72%], [61%], [45%], [18/25]," + NL + ...
        ")" + NL + ...
        NL + ...
        "#figure(" + NL + ...
        "  image(""" + coveragePlot + """, width: 100%)," + NL + ...
        "  caption: [Statement, branch, and MC/DC coverage progression over 10 sprints. " + ...
        "Red dashed line indicates the 80% project target.]," + NL + ...
        ")" + NL + ...
        NL + ...
        "Statement coverage crossed the 80% target in Sprint 8. Branch coverage is " + ...
        "trending toward the target but remains at 72%. MC/DC coverage for safety-critical " + ...
        "modules (ASIL-B) reached 76%, above the 75% interim gate." + NL + ...
        NL + ...
        "= Requirement Traceability" + NL + ...
        NL + ...
        "#figure(" + NL + ...
        "  image(""" + traceabilityPlot + """, width: 100%)," + NL + ...
        "  caption: [Bidirectional traceability between requirements and test cases per ASPICE level.]," + NL + ...
        ")" + NL + ...
        NL + ...
        "Overall traceability stands at *83.6%* (244 of 292 requirements traced). " + ...
        "SWE.6 qualification tests have the lowest traceability at 75.6% due to " + ...
        "pending HIL test specifications." + NL + ...
        NL + ...
        "= Open Items" + NL + ...
        NL + ...
        "#table(" + NL + ...
        "  columns: (auto, 2fr, 1fr, 1fr)," + NL + ...
        "  stroke: rgb(""#1e293b"")," + NL + ...
        "  fill: rgb(""#12121a"")," + NL + ...
        "  table.header(" + NL + ...
        "    [*ID*], [*Description*], [*Severity*], [*Module*]," + NL + ...
        "  )," + NL + ...
        "  [DEF-041], [Torque overshoot on ramp > 500 Nm/s],  [#text(fill: rgb(""#ef4444""))[Critical]], [Motor Control]," + NL + ...
        "  [DEF-038], [GPS timeout not propagated to fusion],  [#text(fill: rgb(""#f59e0b""))[Major]],    [Sensor Fusion]," + NL + ...
        "  [DEF-045], [CAN DLC mismatch on extended frames],   [#text(fill: rgb(""#f59e0b""))[Major]],    [CAN Stack]," + NL + ...
        "  [DEF-047], [Watchdog reset window too narrow],      [#text(fill: rgb(""#ef4444""))[Critical]], [Safety]," + NL + ...
        ")" + NL + ...
        NL + ...
        "= Test Architecture" + NL + ...
        NL + ...
        "#figure(" + NL + ...
        "  oxdraw(```" + NL + ...
        "graph LR" + NL + ...
        "  subgraph APP[Application]" + NL + ...
        "    direction TB" + NL + ...
        "    TORQ[Torque Manager]" + NL + ...
        "    CRUISE[Cruise Control]" + NL + ...
        "    REGEN[Regen Braking]" + NL + ...
        "  end" + NL + ...
        "  subgraph SWC[SWE.4 Unit Components]" + NL + ...
        "    direction TB" + NL + ...
        "    MOT[Motor Control]" + NL + ...
        "    SENS[Sensor Fusion]" + NL + ...
        "    DIAG[Diagnostics]" + NL + ...
        "    PWR[Power Mgmt]" + NL + ...
        "  end" + NL + ...
        "  subgraph INT[SWE.5 Integration]" + NL + ...
        "    direction TB" + NL + ...
        "    CAN[CAN Stack]" + NL + ...
        "    SPI[SPI Driver]" + NL + ...
        "    ADC[ADC Handler]" + NL + ...
        "  end" + NL + ...
        "  subgraph SAF[SWE.6 Safety ASIL-B]" + NL + ...
        "    direction TB" + NL + ...
        "    E2E[E2E Protection]" + NL + ...
        "    MON[Flow Monitor]" + NL + ...
        "    WDG[Watchdog]" + NL + ...
        "    SAFE[Safe State]" + NL + ...
        "  end" + NL + ...
        "  subgraph HW[Hardware MCAL]" + NL + ...
        "    direction TB" + NL + ...
        "    MCAL[AUTOSAR MCAL]" + NL + ...
        "    BSW[Basic SW]" + NL + ...
        "  end" + NL + ...
        "  APP --> SWC" + NL + ...
        "  SWC --> INT" + NL + ...
        "  INT --> HW" + NL + ...
        "  SAF --> HW" + NL + ...
        "  TORQ --> MOT" + NL + ...
        "  CRUISE --> SENS" + NL + ...
        "  REGEN --> PWR" + NL + ...
        "  MOT --> CAN" + NL + ...
        "  SENS --> SPI" + NL + ...
        "  DIAG --> CAN" + NL + ...
        "  PWR --> ADC" + NL + ...
        "  MOT -.->|monitor| E2E" + NL + ...
        "  CAN -.->|monitor| E2E" + NL + ...
        "  DIAG -.->|monitor| MON" + NL + ...
        "  E2E --> SAFE" + NL + ...
        "  MON --> SAFE" + NL + ...
        "  WDG --> SAFE" + NL + ...
        "```)," + NL + ...
        "  caption: [Software architecture from application layer through safety monitoring to hardware abstraction.]," + NL + ...
        ")" + NL + ...
        NL + ...
        "= Verification Method" + NL + ...
        NL + ...
        "Test oracle for boundary value analysis uses the tolerance function:" + NL + ...
        NL + ...
        "$ epsilon(x) = cases(" + NL + ...
        "  0.01 dot |x| &quad upright(""if"") |x| > 1," + NL + ...
        "  10^(-6)      &quad upright(""otherwise"")" + NL + ...
        ") $" + NL + ...
        NL + ...
        "MC/DC coverage computed as:" + NL + ...
        NL + ...
        "$ C_(upright(""MC/DC"")) = (sum_(i=1)^n delta_i) / n $" + NL + ...
        NL + ...
        "where $delta_i = 1$ if condition $i$ independently affects the decision outcome, " + ...
        "and $delta_i = 0$ otherwise." + NL;
end

% -- architecture tab (Mermaid diagram) ------------------------------------

function buildArchTab(panel)
    diagram = ic.Mermaid( ...
        "Value", buildMermaidSource(), ...
        "DarkMode", true, ...
        "ToolbarOnHover", true);
    panel.addChild(diagram);
    diagram.css.fill();
end

function src = buildMermaidSource()
    NL = newline;
    src = "graph LR" + NL + ...
        NL + ...
        "  subgraph APP[""Application""]" + NL + ...
        "    direction TB" + NL + ...
        "    TORQ[Torque Manager]" + NL + ...
        "    CRUISE[Cruise Control]" + NL + ...
        "    REGEN[Regen Braking]" + NL + ...
        "  end" + NL + ...
        NL + ...
        "  subgraph SWC[""SWE.4 -- Unit Components""]" + NL + ...
        "    direction TB" + NL + ...
        "    MOT[Motor Control]" + NL + ...
        "    SENS[Sensor Fusion]" + NL + ...
        "    DIAG[Diagnostics]" + NL + ...
        "    PWR[Power Mgmt]" + NL + ...
        "  end" + NL + ...
        NL + ...
        "  subgraph INT[""SWE.5 -- Integration""]" + NL + ...
        "    direction TB" + NL + ...
        "    CAN[CAN Stack]" + NL + ...
        "    SPI[SPI Driver]" + NL + ...
        "    ADC[ADC Handler]" + NL + ...
        "  end" + NL + ...
        NL + ...
        "  subgraph SAF[""SWE.6 -- Safety / ASIL-B""]" + NL + ...
        "    direction TB" + NL + ...
        "    E2E[E2E Protection]" + NL + ...
        "    MON[Flow Monitor]" + NL + ...
        "    WDG[Watchdog]" + NL + ...
        "    SAFE[Safe State]" + NL + ...
        "  end" + NL + ...
        NL + ...
        "  subgraph HW[""Hardware / MCAL""]" + NL + ...
        "    direction TB" + NL + ...
        "    MCAL[AUTOSAR MCAL]" + NL + ...
        "    BSW[Basic SW]" + NL + ...
        "  end" + NL + ...
        NL + ...
        "  APP --> SWC" + NL + ...
        "  SWC --> INT" + NL + ...
        "  INT --> HW" + NL + ...
        "  SAF --> HW" + NL + ...
        NL + ...
        "  TORQ --> MOT" + NL + ...
        "  CRUISE --> SENS" + NL + ...
        "  REGEN --> PWR" + NL + ...
        "  MOT --> CAN" + NL + ...
        "  SENS --> SPI" + NL + ...
        "  DIAG --> CAN" + NL + ...
        "  PWR --> ADC" + NL + ...
        NL + ...
        "  MOT -.->|monitor| E2E" + NL + ...
        "  CAN -.->|monitor| E2E" + NL + ...
        "  DIAG -.->|monitor| MON" + NL + ...
        "  E2E --> SAFE" + NL + ...
        "  MON --> SAFE" + NL + ...
        "  WDG --> SAFE" + NL + ...
        NL + ...
        "  style APP fill:#1e3a5f,stroke:#3b82f6,color:#93c5fd" + NL + ...
        "  style SWC fill:#1a3328,stroke:#22c55e,color:#86efac" + NL + ...
        "  style INT fill:#2d2344,stroke:#8b5cf6,color:#c4b5fd" + NL + ...
        "  style SAF fill:#3b1c1c,stroke:#ef4444,color:#fca5a5" + NL + ...
        "  style HW fill:#1e1e2e,stroke:#6b7280,color:#9ca3af" + NL + ...
        NL + ...
        "  classDef app fill:#1e3a5f,stroke:#3b82f6,color:#e2e8f0" + NL + ...
        "  classDef swc fill:#1a3328,stroke:#22c55e,color:#e2e8f0" + NL + ...
        "  classDef intg fill:#2d2344,stroke:#8b5cf6,color:#e2e8f0" + NL + ...
        "  classDef saf fill:#3b1c1c,stroke:#ef4444,color:#e2e8f0" + NL + ...
        "  classDef hw fill:#1e1e2e,stroke:#6b7280,color:#94a3b8" + NL + ...
        NL + ...
        "  class TORQ,CRUISE,REGEN app" + NL + ...
        "  class MOT,SENS,DIAG,PWR swc" + NL + ...
        "  class CAN,SPI,ADC intg" + NL + ...
        "  class E2E,MON,WDG,SAFE saf" + NL + ...
        "  class MCAL,BSW hw" + NL;
end

% -- detail drawer ---------------------------------------------------------

function d = buildDetailDrawer(frame)
    d.drawer = ic.Drawer( ...
        "Title", "Test Details", ...
        "Side", "right", ...
        "Size", "md", ...
        "Closable", true);
    frame.addChild(d.drawer);

    col = ic.FlexContainer("Direction", "column", "Gap", 12, "Padding", [12 16]);
    d.drawer.Body.addChild(col);

    d.taskLabel = ic.Label("Text", "", ...
        "Variant", "heading", "Size", "md", "Weight", "bold");
    col.addChild(d.taskLabel);

    detailGrid = ic.GridContainer("Columns", "auto 1fr", "Gap", "6px 12px");
    col.addChild(detailGrid);

    fieldNames = ["Result", "Level", "Module", "Priority", "Last Run"];
    d.vals = {};
    for i = 1:numel(fieldNames)
        lbl = ic.Label("Text", fieldNames(i), "Size", "sm");
        detailGrid.addChild(lbl);
        lbl.css.style("", "opacity", "0.5");
        v = ic.Label("Text", "", "Size", "sm", "Weight", "bold");
        detailGrid.addChild(v);
        d.vals{i} = v;
    end

    d.bar = ic.ProgressBar("Value", 0, "Max", 100, "Variant", "primary", ...
        "Size", "sm", "Striped", true, "Animated", true);
    col.addChild(d.bar);
end

% -- styling ---------------------------------------------------------------

function applyStyle(header, tbl, kpiRow)
    header.row.css.style("", ...
        "borderBottom", "1px solid rgba(255,255,255,0.06)", ...
        "backgroundColor", "rgba(255,255,255,0.02)");
    header.title.css.style("", "color", "#e2e8f0");

    % KPI cards
    kpiRow.row.css.style(" .ic-flex", ...
        "backgroundColor", "rgba(255,255,255,0.03)", ...
        "border", "1px solid rgba(255,255,255,0.06)", ...
        "borderRadius", "8px");

    % table text readability
    tbl.css.style(".ic-tbl__header", ...
        "backgroundColor", "rgba(255,255,255,0.02)", ...
        "borderBottom", "1px solid rgba(255,255,255,0.08)");
    tbl.css.style(".ic-tbl__hcell", ...
        "fontSize", "11px", ...
        "textTransform", "uppercase", ...
        "letterSpacing", "0.5px", ...
        "color", "rgba(255,255,255,0.5)");
    tbl.css.style(".ic-tbl__cell", ...
        "color", "#cbd5e1");
    tbl.css.style(".ic-tbl__row:hover", ...
        "backgroundColor", "rgba(99,102,241,0.06)");
    tbl.css.style(".ic-tbl__row--selected", ...
        "backgroundColor", "rgba(99,102,241,0.1)", ...
        "boxShadow", "inset 3px 0 0 #6366f1");
    tbl.css.style(".ic-tbl__row--striped", ...
        "backgroundColor", "rgba(255,255,255,0.015)");
end

% -- callbacks -------------------------------------------------------------

function wireCallbacks(header, tc, tbl, drawer, frame, sidebar)
    addlistener(header.menuBtn, 'Clicked', @(~,~) sidebar.drawer.open());
    addlistener(tbl, 'SelectionChanged', @(~,e) onRowSelected(e, tbl, drawer));

    tabs = {tc.overviewTab, tc.reportTab, tc.archTab};
    tabIds = cellfun(@(t) t.ID, tabs, 'UniformOutput', false);
    allBtns = sidebar.navBtns;

    % nav buttons -> select tab + highlight
    for i = 1:numel(tabs)
        addlistener(allBtns{i}, 'Clicked', ...
            @(~,~) onNavClicked(tc.container, tabs{i}, sidebar.drawer, allBtns, i));
    end

    % tab changed (by click or programmatic) -> sync nav highlight + toast
    addlistener(tc.container, 'ValueChanged', ...
        @(~,e) onTabChanged(e, frame, allBtns, tabIds));
end

function onNavClicked(tabContainer, tab, drawer, allBtns, idx)
    tabContainer.selectTab(tab);
    drawer.close();
    highlightNav(allBtns, idx);
end

function highlightNav(allBtns, activeIdx)
    for j = 1:numel(allBtns)
        allBtns{j}.css.clearStyle("");
        allBtns{j}.css.style("", "justifyContent", "flex-start", "width", "100%");
        if j == activeIdx
            allBtns{j}.css.style("", ...
                "backgroundColor", "rgba(99,102,241,0.12)", ...
                "color", "#818cf8");
        end
    end
end

function onRowSelected(e, tbl, d)
    sel = e.Data.selection;
    if ~strcmp(sel.type, 'row'), return; end
    if isempty(sel.value), return; end
    rowIdx = sel.value(1);
    if rowIdx < 1 || rowIdx > height(tbl.Data), return; end
    row = tbl.Data(rowIdx, :);
    fprintf("Row %d: %s [%s] %s\n", rowIdx, row.TestCase, row.Result, row.Module);
    d.taskLabel.Text = string(row.TestCase);
    d.vals{1}.Text = string(row.Result);
    d.vals{2}.Text = string(row.Level);
    d.vals{3}.Text = string(row.Module);
    d.vals{4}.Text = string(row.Priority);
    d.vals{5}.Text = string(row.LastRun);
    d.bar.Value = row.Coverage;
    d.drawer.open();
end

function onTabChanged(e, frame, allBtns, tabIds)
    val = string(e.Data.value);
    if val == "", return; end

    % sync nav highlight to whichever tab was selected
    for k = 1:numel(tabIds)
        if val == tabIds{k}
            highlightNav(allBtns, k);
            break;
        end
    end

    frame.addChild(ic.Toast( ...
        "Value", "Switched tab", ...
        "Variant", "info", ...
        "Duration", 2, ...
        "Position", "top"));
end

end
